### ISSUE TITLE
Key prop for child elements

### ISSUE THREAD

**Issue by Rahulzz** [meharbhutta/react-native-fb-collage#1]
Can you add a key prop to the child elements to avoid the warning thrown. Following is what I am facing

<img width="426" alt="Screen Shot 2019-09-13 at 11 57 50 PM" src="https://user-images.githubusercontent.com/20224717/64885667-544dfb00-d682-11e9-9d90-94e153751368.png">

**Comment by Rahulzz** [comment]
Are you guys active on this repo?

**Comment by meharbhutta** [comment]
This issue has been resolved in v1.0.2
